### ISSUE TITLE
Bundle Zotero with Global menu support for Ubuntu 19.04

### ISSUE THREAD

**Issue by ripefig** [retorquere/zotero-jurism-ppa#2]
You just some files from Firefox 52 ESR and libxul.so compiled with global menu support, which you can find [here](https://github.com/ripefig/Firefox-ESR-52-Global-Menu).

**Comment by retorquere** [comment]
Can you see if https://github.com/retorquere/zotero-jurism-ppa/blob/master/install-zotero.py works for you? The installer just calls the script. If it works, I'll upload new packages. I did test by shortcutting some of the tests, but this script I linked to will only actually ask for the new libxul on 19.04 or later. The installer will put zotero into ~/bin/zotero, you can delete that afterward if you want. If you run it as root, it goes to /usr/lib/zotero.

Where did you get 19.04 though? The name suggests it should have been released already but it's not on https://www.ubuntu.com/download/desktop. I

**Comment by ripefig** [comment]
Yup it works, but gives an error at the end:

```
Traceback (most recent call last):
  File "./zot.py", line 188, in <module>
    f.write('MimeType=x-scheme-handler/zotero\n')
ValueError: I/O operation on closed file
```

Proof of result (tested on Gnome, of all places with vala-panel appmenu). So this will work:

![image](https://user-images.githubusercontent.com/45201036/54191043-2c5cbf80-44c6-11e9-827c-c7c5daadb7e4.png)

You still need to tweak the userchrome, by placing:

```css
window[shellshowingmenubar="true"] menubar {
  display: none !important;
}

window[shellshowingmenubar="true"]
toolbar[type="menubar"]:not([customizing="true"]) {
  min-height: 0 !important;
  border: 0 !important;
}
```
 in `~/.zotero/zotero/<profile id>.default/chrome/userChrome.css`.

(this should hide the menubar from the main interface  only if global menu is running.)
